### PR TITLE
Add update cluster

### PR DESCRIPTION
**Pull request by shortdudey123**
- Add update cluster
- Flesh out the table in the README a bit more

### CODE REVIEW

**Comment by kris-lab** [comment]
lgtm!

**Comment by kris-lab** [comment]
Hmm maybe one note. There are resources supported by public [MMS](https://docs.cloud.mongodb.com/reference/api/):
```
Root
Hosts
Agents
Metrics
Clusters
Groups
Users
Alerts
Alert Configurations
Maintenance Windows
Backup Configurations
Snapshot Schedule
Snapshots
Checkpoints
Restore Jobs
Whitelist
Automation Configuration
Automation Status
```

In `readme` we list some of resources we do not support currently but there are much more unsupported by us? What was your idea to add some of them?

**Comment by shortdudey123** [comment]
I added 2 that most people probably would look at.  I can list all of them or pull `Alert Configurations` and `Users` back out, which every you prefer :)

**Comment by kris-lab** [comment]
I would remove them for now:)

**Comment by shortdudey123** [comment]
Updated

**Comment by kris-lab** [comment]
lgtm!

**Comment by kris-lab** [comment]
Thanks again:) !

**Pull request merged**
