### PR TITLE
Add docblocks (return, params) for api

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
I am not sure but they worked better when we checked them on your machine @kris-lab. In my Intellij they seem very limited. Can you check if it works somehow in your env? Thanks.

**Comment by tomaszdurka** [comment]
Another thing I am not sure if all those ids should be `Integer` or rather `String`?

**Comment by kris-lab** [comment]
- All works fine for me!
- well API always return `strings`. `IDs` are clearly a string type on MMS.

**Comment by tomaszdurka** [comment]
Please review.

**Comment by tomaszdurka** [comment]
@kris-lab please review

**Comment by tomaszdurka** [comment]
Should I bump version?

**Comment by kris-lab** [comment]
-  lib/mms/agent.rb : restorejob_create: group_id, cluster_id params as an `string` not `object`?
- lib/mms/agent.rb : alert_ack: returns `TrueClass`?
- lib/mms/cli.rb: print, print_json, print_human: return `string`?

yes, please also bump to `0.1.0`

**Comment by tomaszdurka** [comment]
- agree
- agree
- it puts so it will return nil...

**Pull request merged**
