### PR TITLE
supporting MMS metrics API

### PR DESCRIPTION
**Pull request by itaymendel**
supporting queries on MMS metrics API
does not work with the CLI, only wraps API

### CODE REVIEW

**Comment by kris-lab** [comment]
@itaymendel many thanks for sharing your code. I will have a look asap!

**Comment by kris-lab** [comment]
@itaymendel unfortunately my version of MMS cloud doesn't support metrics via API. We would be very glad if we have some specs to cover this resource. Would you be up to add a few simple tests? Also have you tested this on your production env?

**Comment by itaymendel** [comment]
@kris-lab thanks for you comment. yes i tested it, and actually using it. i'll try and add some tests during the weekend. anyway, this is using this API: https://docs.cloud.mongodb.com/reference/api/metrics/

**Comment by kris-lab** [comment]
@itaymendel sorry for late response and many thanks for your contribution. I will have a look asap.

**Comment by kris-lab** [comment]
@itaymendel I am closing this PR in favour of https://github.com/cargomedia/mms-api/pull/25 

I have added spec and resolved merge conflicts. Hope this is ok with you.

I will let you know soon as the release is done https://github.com/cargomedia/mms-api/issues/24

**Comment by itaymendel** [comment]
@kris-lab thanks for the merge! sorry i didn't write the specs in time

**Pull request merged**
