### PR TITLE
MMS Ticket: Cannot get "restore job" for config server via API

### PR DESCRIPTION
**Pull request by kris-lab**
Ticket: MMSSUPPORT-6493
https://jira.mongodb.org/browse/MMSSUPPORT-6493?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=928365#comment-928365

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam there are finally some good changes on the API. The main difference is clear definition of:
- `restorejob` endpoint for cluster or host
- `snapshot` endpoint for cluster or host

It allows us to differentiate easily between `config-server` or `replica member server`. I have updated some parts of `mms-api` client. Seems to work fine but still need tests and maybe code upgrade.

**Comment by kris-lab** [comment]
@tomaszdurka would you like to say something? review maybe:) ?

**Comment by tomaszdurka** [comment]
Hmmm, I would rather propose to have `_find_by_cluster` and `_find_by_host` public rather than having this crazy signature for `find` method. Wdyt?

Also maybe it should be named `find_via_host` instead of `by`? :panda_face:


Also let's add some docu for new methods (return type).

**Comment by kris-lab** [comment]
`_find_by_cluster` and `_find_by_host` doesn't apply to each type of MMS resource but I agree that it should be done nicer! I am not sure is `MMS::Resource` a right place? Would you keep `self.find` and additionally implement `self.find_via_host` and `self.find_via_cluster`?

**Comment by tomaszdurka** [comment]
I would drop `find` and keep two others :) Well in general static methods are quite bad for testing as they usually rely on global state. Simple stateless methods (aka constructors) ain't so bad.

**Comment by kris-lab** [comment]
@tomaszdurka do you think it is good to change that model now? There are many people who uses this currently?

**Comment by tomaszdurka** [comment]
Well these are all private methods right? So shouldn't be a problem.

**Comment by kris-lab** [comment]
Hmm according to documentation you can e.g.
```
group = MMS::Resource::Group.find(client, 'group_id')
```
which will call internally `self._find` so yes, you are right:) We can refactor some parts. thx

**Comment by tomaszdurka** [comment]
Ah, ok. So `Resource.find` calls `_find` with the same arguments.... so `_find` should be implemented. I am not sure. it's your call I guess.
I would possibly throw in `_find` so you cannot use `find`, but make `_find_via_*` methods public. It's your call though it can stay as is too... :panda_face:

**Comment by kris-lab** [comment]
I am going to merge this as it is now. Currently we have implemented 8 end-points for MMS resources. In 6 of 8 the `_find()` makes totally sense. For 2 of 8 there must be switch for `cluster` or `host` end-point as `snapshot` or `restorejob` can be owned by `cluster` of `host` (e.g. replica member is cluster member and config-server is host only)

**Comment by kris-lab** [comment]
@tomaszdurka please re-open if you see some "dangerous" code!

**Pull request merged**
