### PR TITLE
Prepare to 0.1.0 release

### PR DESCRIPTION
**Pull request by kris-lab**
* [x] optimize exception handling #13 #15
 - [x] error handling for `unauthorized` access `@clinet._get`
* [x] refactor `resource` loader #13 #15 
* [x] refactor `resource` constructor to accept only client and `data` hash #13 
* [x] introduce helper with `print` function for resources (replace cli client usages) https://github.com/cargomedia/mms-api/pull/13
* [x] add tests https://github.com/cargomedia/mms-api/issues/4 #15 
* [x] config file from ~/.mms-api #6 
* [x] docu; docblocks #14

### CODE REVIEW

**Comment by kris-lab** [comment]
@tomaszdurka I think this is good time to make docu more sexy?

**Comment by tomaszdurka** [comment]
Yep, I'm on it now.

**Comment by tomaszdurka** [comment]
Ah so you will bump version here once docu merged? Cool.

**Comment by kris-lab** [comment]
paired with @tomaszdurka

**Pull request merged**
