### PR TITLE
add put

### PR DESCRIPTION
**Pull request by doofdoofsf**
Added the missing `PUT` method. The underlying MMS API uses `PUT` for a few things and it's nice to be able to do `client.put`, `client.get` etc to make direct REST calls for the things not covered by the agent.

### CODE REVIEW

**Comment by kris-lab** [comment]
@doofdoofsf thanks for your contribution. I will have a look asap. For now, I see there is plenty of `rubocop` alerts (see `travis`). Would you be up to resolve and push the changes? Most likely it will require to run `rubocop -a` to auto fix all problems.

**Comment by doofdoofsf** [comment]
@kris-lab thanks for the quick reply. took a look at the build, not quite sure what's going on but nothing there is related to my commit.

**Comment by kris-lab** [comment]
Agree, this is not related to your changes. Basically, `Rubocop` changes the styles and quality checks for time to time which leads to the errors we see now.

I can take over your PR and push fixes, np.

**Comment by doofdoofsf** [comment]
@kris-lab thanks man.

**Comment by njam** [comment]
Maybe we should require a specific rubocop minor version, like
```
s.add_development_dependency 'rubocop', '~> 0.42'
```

**Comment by kris-lab** [comment]
Closing in favor of #31

**Pull request closed without merging**
