### PR TITLE
Added hashes to restore job

### PR DESCRIPTION
**Pull request by Mike-Petersen**
Hi,
after the file is downloaded you can retrieve the hashes of the downloaded file to verify the contents (https://docs.opsmanager.mongodb.com/current/reference/api/restore-jobs/).

Would be nice if you could merge it into the version.

Regards
Mike

### CODE REVIEW

**Comment by kris-lab** [comment]
Thx, will have a look asap.

**Comment by kris-lab** [comment]
In general it looks ok. However the `hashes` filed exists only for downloaded URLs!

> If the corresponding delivery.url has been downloaded, each document in this array is a mapping of a restore file to a hashed checksum. This array is present only after the file is downloaded. Note that for an HTTP restore, this array will only contain a single object representing the hash of the .tar.gz file.

Does it cause any problems for you?

**Comment by Mike-Petersen** [comment]
No, for me everything is fine. It is just set to nil if no hash is present.

**Comment by kris-lab** [comment]
Ok, makes sense. Would you like to bump version from `0.1.4` to `0.1.5` in `lib/mms/version.rb`? I will release asap.

**Comment by Mike-Petersen** [comment]
Hi,
can you please release it?

Thanks

Regards
Mike

**Comment by kris-lab** [comment]
sorry for delay!

**Comment by kris-lab** [comment]
`0.1.5` released

**Pull request merged**
